export const LOGIN_UPDATE = 'LOGIN_UPDATE';
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTHORIZING = 'AUTHORIZING';
export const SAVE_FAIL = 'SAVE_FAIL';

export const POST_CREATE_UPDATE = 'POST_CREATE_UPDATE';
export const POST_CREATE_SAVE = 'POST_CREATE_SAVE';
export const POST_EDIT_UPDATE = 'POST_EDIT_UPDATE';
export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
export const POST_DELETE = 'POST_DELETE';
export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
