export const LOGIN_UPDATE = 'LOGIN_UPDATE';
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTHORIZING = 'AUTHORIZING';
export const SAVE_FAIL = 'SAVE_FAIL';

export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';
export const EMPLOYEE_SAVE_SUCCESS = 'EMPLOYEE_SAVE_SUCCESS';
export const EMPLOYEE_DELETE = 'EMPLOYEE_DELETE';
